apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The application's http port.
    creationTimestamp: 2019-11-19T21:29:38Z
    labels:
      application: openjdk-app
      template: openjdk18-web-basic-s2i
      template.openshift.io/template-instance-owner: b0f0772c-0b13-11ea-bafe-122670964aa1
      xpaas: 1.4.14
    name: openjdk-app
    namespace: dev
    resourceVersion: "38661"
    selfLink: /api/v1/namespaces/dev/services/openjdk-app
    uid: b0f36717-0b13-11ea-bafe-122670964aa1
  spec:
    clusterIP: 172.30.133.223
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentConfig: openjdk-app
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
